### ISSUE TITLE
Modify picture label ?

### ISSUE THREAD

**Issue by Prstork** [clovett/SensorTag-for-Windows#4]
Hello,

I'm using Sensortag and your Windows application for a school project. I would like to modify the text under different pictures and the pictures themself (Barometer, IR Temperature, Humidity, Accelerometer, Gyroscope, Magnetometer, Light) but I can't find the xaml file. Can you explain me where is it or how to do it ?

Thank you very much

**Comment by MartinRomania** [comment]
Hi,
Probably I'm not the right person to answer you because I haven't collaborated with this project but ..

I'm not sure about what you are looking for but you can try with the folder Pages in SharedControls project. I thing in the AccelerometerPage in line 42 there is a textblock with the text Accelerometer. There is also a folder named Assets in each project where you cand find pictures like accelerometer.png. 
And so on
bye

**Comment by Prstork** [comment]
Thanks for your answer !

I saw all pages in SharesControls but unfortunately there is not the one I'm looking for (with all the pictures). It's only the page for the accelerometer or for the humidity for example.

I'm able to change pictures but I have to create a new one with the same name than the previous one, it's probably not the best way. I would like to modify the path of the picture but I can't find it.

Thanks for your help, bye !

**Comment by Prstork** [comment]
I found it, all is in DevicePage.xaml.cs ! There are picture's path and the variable for the text called "Caption" !

Thank you !
